### ISSUE TITLE
Inner classes handled incorrectly

### ISSUE THREAD

**Issue by mikk-normak-cko** [formkiq/graalvm-annotations#1]
Graal requires inner classes to be defined like this:
  {
    "name": "com.amazonaws.services.lambda.runtime.events.SQSEvent$SQSMessage"
  }

but annotation:
@ReflectableClasses({
    @ReflectableClass(
        className=SQSEvent.SQSMessage.class
    )
})
produces output:
  {
    "name": "com.amazonaws.services.lambda.runtime.events.SQSEvent.SQSMessage"
  }
instead

**Comment by mfriesen** [comment]
Been resolved in  

annotationProcessor group: 'com.formkiq', name: 'graalvm-annotations-processor', version: '1.0.1'

https://github.com/formkiq/graalvm-annotations-processor/issues/1
